---
title: "GENOME STATISTICS"
output: html_document
---

(Updated 02/05/2021, lineages assigned by Pangolin v2.1.10)

<br>

```{r, include=F}
# global_options
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=F)
options(scipen=999)
```


```{r}
library(tidyverse)
library(lubridate)
library(plotly)
```


```{r}
all <- readr::read_csv("lineage_line_list.csv") %>% 
    dplyr::filter(!is.na(collection_date)) %>% 
    dplyr::mutate(date=lubridate::date(collection_date)) %>% 
    dplyr::mutate(week= week(collection_date)) %>% 
    dplyr::mutate(date_per_month = as.Date(floor_date(collection_date, "month"))) %>%
    dplyr::mutate(date_of_week = as.Date(floor_date(collection_date, "week"))) %>% 
    dplyr::mutate(lineage=ifelse(is.na(lineage), "0", lineage)) %>% 
    dplyr::mutate(is_B117=as.factor(ifelse(lineage=="B.1.1.7", 1, 0))) %>% 
    dplyr::mutate(is_B1429=as.factor(ifelse(lineage=="B.1.429", 1, 0))) %>%    
    dplyr::mutate(is_P1=as.factor(ifelse(lineage=="P.1", 1, 0))) %>%
    dplyr::mutate(is_B1351=as.factor(ifelse(lineage=="B.1.351", 1, 0))) %>% 
    dplyr::mutate(variant=as.factor(ifelse(lineage %in% c("B.1.1.7", "B.1.429", "B.1.351" ), lineage, "Others"))) %>% 
    dplyr::mutate(variant = factor(variant, levels = c("Others", "B.1.429", "B.1.351", "B.1.1.7")))


```

```{r}
all_table <- all %>% group_by(county, variant) %>% summarize(n=n()) %>% ungroup() %>% 
    dplyr::add_row(county="HOLDER", variant="B.1.429", n=0) %>% 
    dplyr::add_row(county="HOLDER", variant="B.1.351", n=0) %>% 
    dplyr::add_row(county="HOLDER", variant="P.1", n=0) %>% 
    dplyr::add_row(county="HOLDER", variant="B.1.1.7", n=0) %>% 
    spread(key = variant, value = n, fill = as.numeric(0)) %>% 
    rename(County=county) %>% mutate(Total=(B.1.351 + P.1 + B.1.429 + B.1.1.7 + Others)) %>% 
    select(County, Total, B.1.1.7, B.1.351, B.1.429, P.1, Others) %>% 
    filter(County!="HOLDER") 

# create summary table
total_genomes <- sum(all_table$Total)
total_B117 <- sum(all_table$B.1.1.7)
total_B1351 <- sum(all_table$B.1.351)
total_B1429 <- sum(all_table$B.1.429)
total_P1 <- sum(all_table$P.1)

summary_table <- data.frame(V1=c("Total number of genomes:", "Total number of B.1.429 (20C/S:452R, first identified in CA):", "Total number of B.1.1.7 (20I/501Y.V1, first identified in the UK):", "Total number of B.1.351 (20H/501.V2, first identified in South Africa):", "Total number of P.1 (20J/501Y.V3, first identified in Japan/Brazil):"), V2=c(total_genomes, total_B1429, total_B117, total_B1351, total_P1 ))

#knitr::kable(summary_table, col.names = NULL)
```

|||
|------|------|
|__Total number of genomes:__|__`r total_genomes`__|
|__Total number of B.1.429 (20C/S:452R, first identified in CA):__|__`r total_B1429`__|
|__Total number of B.1.1.7 (20I/501Y.V1, first identified in the UK):__|__`r total_B117`__|
|__Total number of B.1.351 (20H/501.V2, first identified in South Africa):__|__`r total_B1351`__|
|__Total number of P.1 (20J/501Y.V3, first identified in Japan/Brazil):__|__`r total_P1`__|

<br>

```{r, plot.width=14, out.width=950 }

all_count <- all %>% 
    dplyr::group_by(date_of_week, variant) %>% 
    dplyr::summarize(n = n()) %>% 
    tidyr::spread(key = variant, value=n, fill = 0) %>% 
    tidyr::gather(key = variant, value=n, -date_of_week ) %>% 
    dplyr::arrange(date_of_week) %>% 
    dplyr::group_by(variant) %>% 
    dplyr::mutate(count = cumsum(n)) %>% 
    dplyr::mutate(variant = factor(variant, levels = c("Others", "B.1.429", "B.1.351", "B.1.1.7")))

p1 <- all_count %>% 
    ggplot() + geom_bar(aes(x=date_of_week, y=count, fill=variant), stat="identity")  +
    scale_x_date(date_breaks = "1 month", date_labels =  "%b")  +
    scale_fill_manual("Variants", values=c("#c7c7c7","#00A1E0", "#007cad","#455156")) +
    theme_light() + ggtitle("Cumulative total sequenced genomes") +
    theme(axis.title.x = element_blank(), axis.text.x=element_text(size=10, face="bold"), axis.text.y=element_text(size=10), axis.title.y=element_text(size=10, face="bold"),
          legend.position = "none") 

p1ly <- ggplotly(p1, tooltip = c("date_of_week","count")) 


p2 <- all_count %>% 
    ggplot() + geom_bar(aes(x=date_of_week, y=count, fill=variant), stat="identity", position = "fill")  +
    scale_x_date(date_breaks = "1 month", date_labels =  "%b")  +
    scale_y_continuous(labels = scales::label_percent()) +
    scale_fill_manual("Variants", values=c("#c7c7c7","#00A1E0", "red","yellow")) +
    theme_light() + 
    theme(axis.title.x = element_blank(), axis.text.x=element_text(size=10, face="bold"), axis.text.y=element_text(size=10), axis.title.y=element_text(size=10, face="bold")) + ylab("Percentage") 

p2ly <- ggplotly(p2, tooltip = c("plotly_label1","count"))

subplot(p1ly, p2ly, margin = 0.04)


```

<br>

```{r, plot.width=14, plot.height=12, out.width=950, out.height=700}
# by county
knitr::kable(all_table)

no_plot <- all_table %>% filter(Total < 20) %>% select(County) %>% rename(county=County)

# need a all county x all dates table
cxd <- all %>% dplyr::select(county, date_of_week) %>% 
    unique() %>% 
    dplyr::anti_join(no_plot) %>% 
    dplyr::mutate(n_holder = 0) %>% 
    tidyr::spread(key=date_of_week, value=n_holder, fill=0) %>% 
    tidyr::gather(key=date_of_week, value=n_holder, -county) %>% 
    dplyr::select(-n_holder) %>% mutate(date_of_week=date(date_of_week))


county_count = all %>% 
    dplyr::anti_join(no_plot) %>% 
    dplyr::select(county, date_of_week, variant) %>% 
    dplyr::group_by(county, date_of_week, variant) %>% 
    dplyr::summarize(n = n()) %>%
    tidyr::spread(key = variant, value=n, fill = 0) %>% 
    dplyr::full_join(cxd) %>% 
    dplyr::mutate_all(~replace(., is.na(.), 0)) %>% 
    tidyr::gather(key = variant, value=n, -date_of_week, -county ) %>% 
    dplyr::arrange(date_of_week) %>% 
    dplyr::group_by(county, variant) %>% 
    dplyr::mutate(count = cumsum(n)) %>% 
    dplyr::mutate(variant = factor(variant, levels = c("Others", "B.1.429", "B.1.351", "B.1.1.7"))) 


p1 <- county_count %>% 
    ggplot() + geom_bar(aes(x=date_of_week, y=count, fill=variant), stat="identity") + 
    facet_wrap(~county, scales = "free_y", ncol=3) +  
    scale_x_date(date_breaks = "1 month", date_labels =  "%b")  +
    scale_fill_manual("Variants", values=c("#c7c7c7","#00A1E0", "red","yellow")) +
    theme_light() + 
    ggtitle("Cumulative total sequenced genomes") +
    theme(axis.title.x = element_blank(), axis.text.x=element_text(angle=60, hjust=1), strip.text.x = element_text(size=9)) + ylab("Count") 

ggplotly(p1)


p2 <- county_count %>% 
    select(-count) %>% rename(count=n) %>% 
    ggplot() + geom_bar(aes(x=date_of_week, y=count, fill=variant), stat="identity") + 
    facet_wrap(~county, scales = "free_y", ncol=3) +   
    scale_x_date(date_breaks = "1 month", date_labels =  "%b")  +
    scale_fill_manual("Variants", values=c("#999999","#007cad", "red","yellow")) +
    theme_light() + 
    ggtitle("Sequenced genomes per week") +
    theme(axis.title.x = element_blank(), axis.text.x=element_text(angle=60, hjust=1), strip.text.x = element_text(size=9)) + ylab("Count") 

ggplotly(p2)


p3 <- county_count %>% 
    rename(percent=n) %>% 
    ggplot() + geom_bar(aes(x=date_of_week, y=percent, fill=variant), stat="identity", position="fill") + 
    facet_wrap(~county, scales = "free_y", ncol=3) +   
    scale_x_date(date_breaks = "1 month", date_labels =  "%b")  +
    scale_y_continuous(labels = scales::label_percent()) +
    scale_fill_manual("Variants", values=c("#999999","#007cad", "red","yellow")) +
    theme_light() + ggtitle("Percent variant per week") +
    theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x=element_text(angle=60, hjust=1), strip.text.x = element_text(size=9))  

ggplotly(p3)
```

